import { StitchesRegistry } from '@/styles/global'
import { Roboto } from 'next/font/google'
import { ReactNode } from 'react'
import { NextAuthProvider } from './providers'
import { Metadata } from 'next'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Ignite Call',
  description: 'Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'pt_BR',
    url: 'https://ignite-call.rocketseat.com.br',
    siteName: 'Ignite Call',
  },
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthProvider>
          <StitchesRegistry>{children}</StitchesRegistry>
        </NextAuthProvider>
      </body>
    </html>
  )
}
