import { StitchesRegistry } from '@/styles/global'
import { Roboto } from 'next/font/google'
import { ReactNode } from 'react'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Ignite Call',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StitchesRegistry>{children}</StitchesRegistry>
      </body>
    </html>
  )
}
